Большие перемены (часть 1)
htmlacademy-ecmascript/1967081-big-trip-17 pull request #9
Opened 2022-05-29 13:19 UTC by Cr4zyGleb

2022-05-29 15:28 UTC, ekazakov requested changes

2022-05-29 15:28 UTC, ekazakov commented on src/presenter/trip-presenter.js
> +    this.#tripListComponent = updateItem(this.#points , updatedPoint);
Тут опечатка, д.б. 
```js
this.#points = updateItem(this.#points , updatedPoint);
```

2022-05-29 15:28 UTC, ekazakov commented on src/presenter/trip-presenter.js
> +  // };
Тут все ок

2022-05-29 15:28 UTC, ekazakov commented on src/presenter/trip-point-presenter.js
> +  // };
Тут все ок

2022-05-29 15:28 UTC, ekazakov commented on src/presenter/trip-point-presenter.js
> +    const onEscKeyDown = (evt) => {
Сейчас если 1 раз свернуть-развернуть форму, а затем нажать Esc то возникнет ошибка. Вынеси `onEscKeyDown` — в метод компонента, и перенеси отписку в метод `replaceFormToPoint`

2022-05-29 17:56 UTC, Cr4zyGleb commented on src/presenter/trip-point-presenter.js
> +      return 1;
+

2022-05-29 18:01 UTC, Cr4zyGleb commented on src/presenter/trip-presenter.js
> +    this.#tripListComponent = updateItem(this.#points , updatedPoint);
+
Непонятно почему тогда и так и так работает)

2022-05-30 07:14 UTC, ekazakov commented on src/presenter/trip-presenter.js
> +    this.#tripListComponent = updateItem(this.#points , updatedPoint);
`this.#tripListComponent` — передается в презентер точки маршрута при создании. И изначально там верное значение. Позже когда добавишь перерисовку всего списка точек, презентеры будут создаваться заново и тогда уже вылезет ошибка

2022-05-30 18:19 UTC, merged